name: ipsb_visitor_app
description: IPSB Visitor App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following is used for state management
  get:

  # The following is used for pick image from mobile device
  image_picker: ^0.8.0+3

  # Add alert widgets
  rflutter_alert: ^2.0.2

  # Use with the sliding up a paned to show infomation when searching
  sliding_up_panel: ^2.0.0+1

  # Get more icons to use
  font_awesome_flutter: ^9.1.0

  # Date formatter
  intl: ^0.17.0

  # QR Code Generator
  qr_flutter: ^4.0.0

  # Dashed line
  path_drawing: ^0.5.1

  # Glowing point
  avatar_glow: ^2.0.1

  # Glowing anything
  flutter_glow: ^0.2.0

  # grid view animation
  flutter_staggered_animations: ^1.0.0

  # tab view
  flutter_tab_indicator_styler: ^2.0.0

  # Bottom sheet
  solid_bottom_sheet: ^0.1.10

  # FLutter bullet list
  flutter_bullet_list: ^0.0.4

  # Badges
  badges: ^2.0.1

  # Bottom bar
  salomon_bottom_bar: ^3.1.0

  # App bar search
  material_floating_search_bar: ^0.3.4

  # Smooth page indicator
  smooth_page_indicator: ^1.0.0+2

  # Dropdown plus
  dropdown_plus: ^0.0.9

  # Date time picker
  date_time_picker: ^2.1.0

  # Animated floating buttons
  animated_floating_buttons: ^0.0.1

  # Flutter slidable
  flutter_slidable: ^0.6.0

  # Menu button
  menu_button: ^1.4.2+1

  # Carousel
  carousel_slider: ^4.0.0

  # Svg display
  flutter_svg: ^0.22.0

  # Toast
  bot_toast: ^4.0.1

  #Rating
  flutter_rating_bar: ^4.0.0

  #Get current location
  geocode: ^1.0.1
  geolocator: ^7.4.0
  url_launcher: ^6.0.9
  location: ^4.3.0

  # Login with google
  google_sign_in: ^5.0.7
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0

  # UI for phone verify
  pin_code_fields: ^7.3.0

  # Hive for local db
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2

  # Secure storage for storing credentials
  flutter_secure_storage: ^4.2.1

  #Bottom sheet modal
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The following provides annotations help convert json to object
  json_serializable: ^4.1.3
  # The following helps generate .part code
  build_runner: ^1.0.0
  # Hive generator
  hive_generator: ^1.1.0
  #Signin button
  flutter_signin_button: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
